name: 'codewatchers'
description: 'Set PR assignees based on a CODEOWNERS file'
author: 'dovetail'
inputs:
  github-token:
    required: true
    description: 'Auth token with permissions to label PR '
  codewatchers-filename:
    required: false
    description: 'Filename of codewatchers file.'
    default: 'CODEWATCHERS'
runs:
  using: 'node16'
  main: 'dist/index.js'
